### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by yepelinux** [LukBukkit/action-pr-limits#17]
Documentation says "The inputs whitelist and blacklist are deprecated." but it won't work if you dont use it.

![image](https://user-images.githubusercontent.com/660790/164767593-1a6ab883-9b0b-4b89-91fe-d99d5017cb5e.png)

but when I change it to blacklist it filters the branch OK.

![image](https://user-images.githubusercontent.com/660790/164767756-00a793f6-200b-4dbe-ad80-fcf2f811be85.png)

**Comment by yepelinux** [comment]
This is the working configuration

![image](https://user-images.githubusercontent.com/660790/164767925-0987b5d5-20dc-4a5b-a26c-4904aabcfbe8.png)

**Comment by lukbukkit** [comment]
Thanks for your issue report. 

The documentation of GitHub Action states that the major version tag `v1` should always point to the latest release of the major version: https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-tags-for-release-management. I did not update this tag and therefore you've used the old version.

I've updated the `v1` tag to the latest version. Please try again, to see if it now works.

**Comment by lukbukkit** [comment]
I assume this fix worked. Therefore, I'm closing this issue
