### ISSUE TITLE
Update node to v16

### ISSUE THREAD

**Issue by Guate-Jorge** [LukBukkit/action-pr-limits#19]
I'm getting this warning from Github `Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: LukBukkit/action-pr-limits`

[Leaving the source from GH](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)

Could you please update this action in order to use node v16 instead v12?

Thank you!

**Comment by lukbukkit** [comment]
Hello Jorge, 
thanks for bringing this issue to my attention. I'll try to fix it.

**Comment by lukbukkit** [comment]
The [latest release](https://github.com/LukBukkit/action-pr-limits/releases/tag/v1.2.0) of this action now uses Node16 as its runtime. If you use the `@v1` tag to include the action, there should be nothing to do on your end as it also references to the latest release.

Thanks for your patience :)
