### ISSUE TITLE
Pattern Matching for Branch Names

### ISSUE THREAD

**Issue by hoangvu-healthRFID** [LukBukkit/action-pr-limits#9]
Hi @LukBukkit ,

Your github action is very useful and this what I've been looking for a long time. If you can have some update such as allow pattern in the name of the branch, it will be more flexible (eg: development*: allow all branch start with development)  

Looking for the next update,
Regards

**Comment by lukbukkit** [comment]
Yeah, that's a good idea, thanks for your post. 
Currently I'm very busy with my studies and work. Maybe I'll can find some time in the coming months.
If you want, you're always welcome to implement the feature yourself and create a pull request.

**Comment by lukbukkit** [comment]
I've implemented this feature. I recommend that you try the new [version 1.1.0](https://github.com/LukBukkit/action-pr-limits/releases/tag/v1.1.0).
